title:        Free To Feel
tagline:      'Feel the life color'
description:  "Find a way to record my work and life. "
url:          "http://www.freetofeel.com/"
author:
  name: 'Joshua Chi'
  email: "joshokn@gmail.com"
markdown: rdiscount
pygments: true
paginate: true
url: http://freetofeel.com
name: Joshua Chi
email: joshokn@gmail.com
paginate: 7
feedurl: /feed/
