title:        'Free To Feel'
tagline:      'Free To Feel'

site_keywords:   "technical, entrepreneur, consulting, blog, personal, life, work, freelancer"
description:  "Heading to entrepreneur."

url:          "http://www.freetofeel.com/"
safe:         false

author:
  name: 'Joshua Chi'
  email: "joshokn@gmail.com"
markdown: rdiscount
highlighter: true
paginate: true
url: http://freetofeel.com
name: Joshua Chi
email: joshokn@gmail.com
paginate: 7
feedurl: /feed/
paginate_per_category: true
default_category: "en"
